from enum import Enum


# Class-based enum definition
class FunctionType(Enum):
    CELU_LAYER = "celu_layer"
    ELU_LAYER = "elu_layer"
    GELU_LAYER = "gelu_layer"
    GLU_LAYER = "glu_layer"
    HARD_SIGMOID_LAYER = "hard_sigmoid_layer"
    HARD_SILU_LAYER = "hard_silu_layer"
    CONV_TRANSPOSE = "convTranspose"
    GELU = "gelu"
    PYTHON_FUNCTION = "python_function"
    PYTHON_CLASS = "python_class"
    DATA_WRAPPER_G = "DataWrapperG"
    ADD_TEXT = "addText"
    ADD_VECTORS = "AddVectors"
    GENERATE_RANDOM = "generateRandome"
    FLATTEN_LAYER = "flattenLayer"
    DENSE = "denseLayer"
    MAX_POOL_LAYER = "maxPoolLayer"
    RELU = "relu"
    CONV = "nn.Conv"
    SELF = "self"
    BATCH_NORM = "batchNorm"
    AVERAGE_POOL = "averagePool"
    DROPOUT = "dropout"
    TANH = "tanh"
    SIGMOID = "sigmoid"
    RNN = "rnn"
    DATA_BATCHING_BLOCK = "dataBatchingBlock"
    DATA_LOADER_BLOCK = "dataLoaderBlock"
    DATA_SELECTION_BLOCK = "dataselectionBlock"
    DATA_PREPROCESSING_BLOCK = "dataPreprocessingBlock"
    DATA_SHUFFLING_BLOCK = "dataShufflingBlock"
    TRANSFORMATIONS_BLOCK = "transformationsBlock"
    SPLIT_DATA_BLOCK = "splitDataBlock"
    LOSS_FUNCTION_BLOCK = "lossFunctionBlock"
    OPTIMIZER_BLOCK = "optimizerBlock"
    TRAINING_STEP_BLOCK = "trainingStepBlock"
    TRAINING_LOOP_BLOCK = "trainingLoopBlock"
    EVALUATION_BLOCK = "evaluationBlock"
    PYTHON_CLASS_ATTRIBUTE = "python_class_attribute"
    PYTHON_RETURN = "python_return"
    NN_COMPACT = "nn_compact"
    SET_VARIABLE_BLOCK = "setVariableBlock"
    GET_VARIABLE_BLOCK = "getVariableBlock"
